# Generated by Django 5.0.4 on 2024-09-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanresult",
            name="alias",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="scanresult",
            name="mac_address",
            field=models.CharField(max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name="scanresult",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
