VERSION = "1.2.9"  # Increment this version number
APP_NAME = "fast-ip-scanner"
APP_DISPLAY_NAME = "Fast IP Scanner"
DESCRIPTION = "A clean, user-friendly web interface for fast IP scanning, port scanning, and network analysis."
SITE_HEADER = APP_DISPLAY_NAME
AUTHOR = "Justin Faulk"
AUTHOR_EMAIL = "deww1434@gmail.com"
URL = "https://github.com/JFaulk1434/fastipscanner"
PORT = 8099
