# Generated by Django 5.0.4 on 2024-09-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanner", "0002_scanresult_alias_alter_scanresult_mac_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanresult",
            name="open_ports",
            field=models.TextField(blank=True),
        ),
    ]
