# Generated by Django 5.0.4 on 2024-09-17 14:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanner", "0003_scanresult_open_ports"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanresult",
            name="last_seen",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
