name: Build and Release

permissions:
  contents: write

on:
  release:
    types: [created]

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Debug environment
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          dir
          echo "Python version:"
          python --version
          echo "Django version:"
          python -c "import django; print(django.__version__)"
      - name: Collect static files
        run: |
          python network_scanner/manage.py collectstatic --noinput --verbosity 2
          echo "Contents of project root after collectstatic:"
          dir
          echo "Contents of network_scanner directory:"
          dir network_scanner
      - name: Build with PyInstaller
        run: |
          pyinstaller --name=FastIPScanner --onefile --windowed `
            --add-data "network_scanner;network_scanner" `
            --add-data "network_scanner/network_scanner/app_info.py;network_scanner" `
            --add-data "network_scanner/staticfiles;staticfiles" `
            --add-data "network_scanner/scanner/migrations;network_scanner/scanner/migrations" `
            network_scanner/manage.py
      - name: Install Inno Setup
        run: choco install innosetup -y
      - name: Get App Info
        run: |
          python get_app_info.py
          if ($LASTEXITCODE -ne 0) {
            exit $LASTEXITCODE
          }
          python get_app_info.py > app_info.txt
          echo "APP_INFO=$(cat app_info.txt)" >> $env:GITHUB_ENV
      - name: Create Inno Setup Installer
        run: |
          dir dist
          iscc ${{ env.APP_INFO }} nettools_setup.iss
      - name: Upload Windows Installer
        uses: actions/upload-artifact@v4
        with:
          name: FastIPScanner-Installer.exe
          path: ./Output/FastIPScanner_setup_*.exe

  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          brew install create-dmg
      - name: Build with PyInstaller
        run: |
          pyinstaller --name=FastIPScanner --onefile --windowed \
            --add-data "network_scanner:network_scanner" \
            --add-data "network_scanner/network_scanner/app_info.py:network_scanner" \
            network_scanner/manage.py
      - name: Create DMG
        run: |
          create-dmg \
            --volname "Fast IP Scanner Installer" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --icon "FastIPScanner.app" 200 190 \
            --hide-extension "FastIPScanner.app" \
            --app-drop-link 600 185 \
            "FastIPScanner-Installer.dmg" \
            "dist/FastIPScanner.app"
      - name: Upload macOS Installer
        uses: actions/upload-artifact@v4
        with:
          name: FastIPScanner-Installer.dmg
          path: ./FastIPScanner-Installer.dmg
